import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LINK from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>{/* <-- BODY-tagget starter her */}
        <header>header
          <nav>
            <LINK href="/contact">contact</LINK>
            <LINK href="/time">time</LINK>
          </nav>
        </header>
        <main>
        {children} {/* <-- Her bliver children indsat */}
        </main>
        <footer>footer</footer>
      </body>
    </html>
  );
}

/* Hvad bruges layout.tsx til?

Definerer den overordnede struktur for alle sider i en App Router mappe (app/)

Alt indhold på de underliggende sider bliver indsat i {children}

Kan indeholde global CSS, fonts, meta-data, header/footer osv.

Løfter layout-kode én gang, så du ikke behøver at gentage HTML-struktur på alle sider */